language: cpp
dist: bionic

matrix:
    include:

        - os: linux
          addons:
              apt:
                  packages:
                      - g++-7
          env:
              - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

        - os: linux
          addons:
              apt:
                  packages:
                      - clang-7
                      - llvm-7-dev
          env:
              - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

branches:
    only:
        - master

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo sed -i '/^Defaults\tsecure_path.*$/ d' /etc/sudoers
    - sudo apt-get update -y
    - sudo apt-get install -y libgtest-dev valgrind cmake clang-tidy-8 expect
    - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
    - sudo tar xf release-1.7.0.tar.gz
    - cd googletest-release-1.7.0
    - sudo mkdir build; cd build
    - sudo cmake -DBUILD_SHARED_LIBS=ON -DBUILD_GMOCK=OFF ..
    - sudo make
    - sudo cp -a include/gtest /usr/include
    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
    - pip install compiledb --user
    - cd "${TRAVIS_BUILD_DIR}"

before_script:
    - compiledb -n make
    - make -DGTEST_LIB_PATH=/usr/lib -DGTEST_INCLUDE_PATH=/usr/include

script:
    - ./build/test
    - ./build/test_debug
    - ./tests/run_perft_tests.sh release weights/basic.w
    - ./tests/run_search_tests.sh release weights/basic.w
