language: cpp
compiler:
    - gcc
    - clang

dist: bionic

branches:
    only:
        - master

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6.0
        packages:
            - g++-7.4
            - clang-6.0

install:
    - "[ $CXX = g++ ] && export CXX=g++-7.4 || true"
    - "[ $CXX = clang++ ] && export CXX=clang++-6.0 || true"


before_install:
    - sudo apt-get update -y
    - sudo apt-get install -y libgtest-dev valgrind cmake clang-tidy-8 expect
    - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
    - sudo tar xf release-1.7.0.tar.gz
    - cd googletest-release-1.7.0
    - sudo cmake -DBUILD_SHARED_LIBS=ON .
    - sudo make
    - sudo cp -a include/gtest /usr/include
    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
    - pip install compiledb --user
    - cd "${TRAVIS_BUILD_DIR}"

before_script:
    - compiledb -n make
    - make

script:
    - ./build/test
    - ./build/test_debug
    - ./run_test_scripts.sh release
