language: cpp
dist: bionic

matrix:
    include:

        - os: linux
          addons:
              apt:
                  packages:
                      - g++-7
          env:
              - CC=gcc-7 CXX=g++-7

        - os: linux
          addons:
              apt:
                  packages:
                      - clang-7
                      - llvm-7-dev
          env:
              - CC=clang-7 CXX=clang++-7

branches:
    only:
        - master

before_install:
    - sudo sed -i '/^Defaults\tsecure_path.*$/ d' /etc/sudoers
    - sudo apt-get update -y
    - sudo apt-get install -y libgtest-dev valgrind cmake clang-tidy-8 expect
    - sudo wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
    - sudo tar xf release-1.10.0.tar.gz
    - cd googletest-release-1.10.0
    - sudo mkdir build; cd build
    - sudo cmake -DBUILD_SHARED_LIBS=ON -DBUILD_GMOCK=OFF ..
    - sudo make
    - sudo make install
    - pip install compiledb --user
    - cd "${TRAVIS_BUILD_DIR}"

before_script:
    - export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
    - compiledb -n make
    - make engine GTEST_LIB_PATH=/usr/local/lib GTEST_INCLUDE_PATH=/usr/local/include CC=${CC} CXX=${CXX}
    - make engine_debug GTEST_LIB_PATH=/usr/local/lib GTEST_INCLUDE_PATH=/usr/local/include CC=${CC} CXX=${CXX}
    - make test GTEST_LIB_PATH=/usr/local/lib GTEST_INCLUDE_PATH=/usr/local/include CC=${CC} CXX=${CXX}
    - make test_debug GTEST_LIB_PATH=/usr/local/lib GTEST_INCLUDE_PATH=/usr/local/include CC=${CC} CXX=${CXX}

script:
    - ./build/tests
    - ./build/tests_debug
    - ./tests/run_perft_tests.sh release
    - ./tests/run_search_tests.sh release
