name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install GoogleTest
      run:  apt-get update -y && \
            apt-get install -y libgtest-dev valgrind cmake clang-tidy-8 expect && \
            wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz && \
            tar xf release-1.10.0.tar.gz && \
            cd googletest-release-1.10.0 && \
            mkdir build; cd build && \
            cmake -DBUILD_SHARED_LIBS=ON -DBUILD_GMOCK=OFF .. && \
            make && \
            make install
      
    - name: Install dependencies
      run: make
