name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GoogleTest
      run: |
        wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        tar xf release-1.10.0.tar.gz
        cd googletest-release-1.10.0
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=ON -DBUILD_GMOCK=OFF ..
        sudo make install

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build
      run: make

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
        ./build/tests
        ./build/tests_debug
        ./tests/run_perft_tests.sh release
        ./tests/run_search_tests.sh release
